"""add new_hire_reported_at to employees

Revision ID: 04957702e756
Revises: 872e8e2838df
Create Date: 2026-06-23 00:23:26.713559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '04957702e756'
down_revision: Union[str, None] = '872e8e2838df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('new_hire_reported_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'new_hire_reported_at')
    # ### end Alembic commands ###
