"""initial schema

Revision ID: 7bc3e26e0a82
Revises: 
Create Date: 2026-05-14 23:05:25.289427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7bc3e26e0a82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
