"""add indexes to FK and frequently filtered columns

Revision ID: c52a89761498
Revises: 04957702e756
Create Date: 2026-06-23 23:02:22.251449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c52a89761498'
down_revision: Union[str, None] = '04957702e756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_client_liabilities_company_id'), 'client_liabilities', ['company_id'], unique=False)
    op.create_index(op.f('ix_client_liabilities_pay_period_id'), 'client_liabilities', ['pay_period_id'], unique=False)
    op.create_index(op.f('ix_client_liabilities_paycheck_id'), 'client_liabilities', ['paycheck_id'], unique=False)
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.create_index(op.f('ix_pay_periods_company_id'), 'pay_periods', ['company_id'], unique=False)
    op.create_index(op.f('ix_pay_periods_pay_date'), 'pay_periods', ['pay_date'], unique=False)
    op.create_index(op.f('ix_pay_periods_status'), 'pay_periods', ['status'], unique=False)
    op.create_index(op.f('ix_paycheck_lines_paycheck_id'), 'paycheck_lines', ['paycheck_id'], unique=False)
    op.create_index(op.f('ix_paychecks_employee_id'), 'paychecks', ['employee_id'], unique=False)
    op.create_index(op.f('ix_paychecks_pay_period_id'), 'paychecks', ['pay_period_id'], unique=False)
    op.create_index(op.f('ix_paychecks_status'), 'paychecks', ['status'], unique=False)
    op.create_index(op.f('ix_timesheets_employee_id'), 'timesheets', ['employee_id'], unique=False)
    op.create_index(op.f('ix_timesheets_pay_period_id'), 'timesheets', ['pay_period_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheets_pay_period_id'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_employee_id'), table_name='timesheets')
    op.drop_index(op.f('ix_paychecks_status'), table_name='paychecks')
    op.drop_index(op.f('ix_paychecks_pay_period_id'), table_name='paychecks')
    op.drop_index(op.f('ix_paychecks_employee_id'), table_name='paychecks')
    op.drop_index(op.f('ix_paycheck_lines_paycheck_id'), table_name='paycheck_lines')
    op.drop_index(op.f('ix_pay_periods_status'), table_name='pay_periods')
    op.drop_index(op.f('ix_pay_periods_pay_date'), table_name='pay_periods')
    op.drop_index(op.f('ix_pay_periods_company_id'), table_name='pay_periods')
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_index(op.f('ix_client_liabilities_paycheck_id'), table_name='client_liabilities')
    op.drop_index(op.f('ix_client_liabilities_pay_period_id'), table_name='client_liabilities')
    op.drop_index(op.f('ix_client_liabilities_company_id'), table_name='client_liabilities')
    # ### end Alembic commands ###
